builders:
  auto_channel_builder:
    import: "package:auto_channel_builder/auto_channel.dart"
    builder_factories: ["autoChannel"]
    build_extensions: {".dart": [".auto_channel.dart"]}
    auto_apply: dependents
    build_to: source