builders:
  flutterbuff_builder:
    import: "package:flutterbuff_builder/builders/flutterbuff_generator.dart"
    builder_factories: ["flutterbuffApiGenerator"]
    build_extensions: {".dart": [".flutterbuff.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: [":cleanup"]
post_process_builders:
  cleanup:
    import: "package:flutterbuff_builder/builders/flutterbuff_generator.dart"
    builder_factory: "cleanupGenerator"
    input_extensions: [".java"]
