builders:
  auto_channel_builder:
    import: "package:auto_channel_builder/builders/auto_channel_generator.dart"
    builder_factories: ["autoChannelGenerator"]
    build_extensions: {".dart": [".auto_channel.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: [":cleanup"]
post_process_builders:
  cleanup:
    import: "package:auto_channel_builder/builders/auto_channel_generator.dart"
    builder_factory: "cleanupGenerator"
    input_extensions: [".java"]