builders:
  flutterbuff_struct_builders:
    applies_builders: [":cleanup"]
    auto_apply: dependents
    build_extensions: {".dart": ["flutterbuff.dart"]}
    build_to: source
    builder_factories: ["flutterbuffStructGenerator"]
    import: "package:flutterbuff_builders/flutterbuff_struct_generator.dart"
    runs_before: [":flutterbuff_api_builders"]
  flutterbuff_api_builders:
    applies_builders: [":cleanup"]
    auto_apply: dependents
    build_extensions: {".dart": [".flutterbuff_api.dart"]}
    build_to: source
    builder_factories: ["flutterbuffApiGenerator"]
    import: "package:flutterbuff_builders/flutterbuff_api_generator.dart"
    required_inputs: [".flutterbuff.dart"]
post_process_builders:
  cleanup:
    builder_factory: "cleanupGenerator"
    import: "package:flutterbuff_builders/flutterbuff_api_generator.dart"
    input_extensions: [".java"]
