name: flutterbuff_builders
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.1.6
  source_gen: ^0.9.4+4
  tuple: ^1.0.2
  analyzer: ^0.38.1
  flutterbuff_annotation:
    path: ../flutterbuff_annotation
